"""
Report Generator Module
Generates HTML and text reports for all scan results
"""

import json
import os
from datetime import datetime


class ReportGenerator:
    def __init__(self, output_dir: str = "reports"):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def generate_html_report(self, scan_data: dict, report_type: str = "general") -> str:
        """Generate a beautiful HTML report"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"{self.output_dir}/cyberguard_{report_type}_{timestamp}.html"
        target = scan_data.get("target", "Unknown")

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CyberGuard Pro — Security Report</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: #0a0a0a;
            color: #e0e0e0;
            line-height: 1.6;
        }}
        .header {{
            background: linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%);
            padding: 40px;
            text-align: center;
            border-bottom: 3px solid #e94560;
        }}
        .header h1 {{ color: #e94560; font-size: 2.5em; margin-bottom: 10px; }}
        .header p {{ color: #a0a0b0; font-size: 1.1em; }}
        .badge {{
            display: inline-block;
            background: #e94560;
            color: white;
            padding: 4px 12px;
            border-radius: 20px;
            font-size: 0.85em;
            margin: 5px 3px;
        }}
        .container {{ max-width: 1100px; margin: 0 auto; padding: 30px 20px; }}
        .summary-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
            margin: 30px 0;
        }}
        .stat-card {{
            background: #1a1a2e;
            border: 1px solid #333;
            border-radius: 12px;
            padding: 25px;
            text-align: center;
            border-top: 3px solid #e94560;
        }}
        .stat-card .number {{ font-size: 2.5em; font-weight: bold; color: #e94560; }}
        .stat-card .label {{ color: #888; margin-top: 5px; }}
        .section {{
            background: #111;
            border: 1px solid #222;
            border-radius: 12px;
            margin: 20px 0;
            overflow: hidden;
        }}
        .section-header {{
            background: #1a1a2e;
            padding: 15px 25px;
            border-bottom: 1px solid #333;
            display: flex;
            align-items: center;
            gap: 10px;
        }}
        .section-header h2 {{ color: #e94560; font-size: 1.2em; }}
        .section-body {{ padding: 25px; }}
        table {{ width: 100%; border-collapse: collapse; }}
        th {{
            background: #1a1a2e;
            padding: 12px 15px;
            text-align: left;
            color: #e94560;
            border-bottom: 2px solid #333;
        }}
        td {{ padding: 12px 15px; border-bottom: 1px solid #1e1e1e; }}
        tr:hover {{ background: #1a1a2e; }}
        .severity-critical {{ color: #ff4444; font-weight: bold; }}
        .severity-high {{ color: #ff8800; font-weight: bold; }}
        .severity-medium {{ color: #ffcc00; }}
        .severity-low {{ color: #44bb44; }}
        .open {{ color: #44ff44; }}
        .closed {{ color: #ff4444; }}
        .tag {{
            display: inline-block;
            background: #1a1a2e;
            border: 1px solid #333;
            padding: 2px 8px;
            border-radius: 4px;
            font-size: 0.8em;
            margin: 2px;
        }}
        .footer {{
            text-align: center;
            padding: 30px;
            color: #444;
            border-top: 1px solid #222;
            margin-top: 40px;
        }}
        code {{
            background: #1a1a2e;
            padding: 2px 6px;
            border-radius: 4px;
            font-family: monospace;
            font-size: 0.9em;
        }}
    </style>
</head>
<body>
<div class="header">
    <h1>🛡️ CyberGuard Pro</h1>
    <p>Security Assessment Report</p>
    <p style="margin-top:15px;">
        <span class="badge">Target: {target}</span>
        <span class="badge">Generated: {scan_data.get('timestamp', datetime.now().strftime('%Y-%m-%d %H:%M:%S'))}</span>
        <span class="badge">Type: {report_type.upper()}</span>
    </p>
</div>

<div class="container">
    {self._build_report_sections(scan_data, report_type)}
</div>

<div class="footer">
    <p>Generated by CyberGuard Pro v1.0.0 | For authorized use only</p>
    <p style="margin-top:5px; font-size:0.85em;">⚠️ This report is confidential. Handle with care.</p>
</div>
</body>
</html>"""

        with open(filename, "w", encoding="utf-8") as f:
            f.write(html)
        return filename

    def _build_report_sections(self, data: dict, report_type: str) -> str:
        sections = ""

        # Network scan section
        if "open_ports" in data:
            ports = data["open_ports"]
            rows = "".join([
                f"""<tr>
                    <td>{p['port']}</td>
                    <td class="open">{p['state'].upper()}</td>
                    <td>{p['service']}</td>
                    <td><code>{p.get('banner', 'N/A')[:50]}</code></td>
                </tr>""" for p in ports
            ]) if ports else "<tr><td colspan='4'>No open ports found</td></tr>"

            sections += f"""
<div class="section">
    <div class="section-header"><h2>🔍 Network Scan Results</h2></div>
    <div class="section-body">
        <p>Host: <strong>{data.get('target')}</strong> | 
           Status: <strong class="open">{'ALIVE' if data.get('alive') else 'DOWN'}</strong> | 
           Open Ports: <strong>{len(ports)}</strong></p>
        <br>
        <table>
            <tr><th>Port</th><th>State</th><th>Service</th><th>Banner</th></tr>
            {rows}
        </table>
    </div>
</div>"""

        # Web vulnerabilities section
        if "vulnerabilities" in data:
            vulns = data["vulnerabilities"]
            headers = data.get("security_headers", {})
            missing = headers.get("missing", {})

            vuln_rows = "".join([
                f"""<tr>
                    <td class="severity-{v['severity'].lower()}">{v['severity']}</td>
                    <td>{v['type']}</td>
                    <td><code>{v.get('parameter', 'N/A')}</code></td>
                    <td style="word-break:break-all; font-size:0.85em;">{v['url'][:60]}...</td>
                </tr>""" for v in vulns
            ]) if vulns else "<tr><td colspan='4'>No vulnerabilities found</td></tr>"

            missing_rows = "".join([
                f"<tr><td><code>{h}</code></td><td>{d}</td></tr>"
                for h, d in missing.items()
            ])

            sections += f"""
<div class="section">
    <div class="section-header"><h2>🌐 Web Vulnerability Scan</h2></div>
    <div class="section-body">
        <h3 style="color:#e94560; margin-bottom:15px;">Vulnerabilities Found: {len(vulns)}</h3>
        <table>
            <tr><th>Severity</th><th>Type</th><th>Parameter</th><th>URL</th></tr>
            {vuln_rows}
        </table>
        <br>
        <h3 style="color:#e94560; margin-bottom:15px;">Missing Security Headers: {len(missing)}</h3>
        <table>
            <tr><th>Header</th><th>Description</th></tr>
            {missing_rows}
        </table>
    </div>
</div>"""

        # OSINT section
        if "dns_records" in data:
            dns = data["dns_records"]
            subdomains = data.get("subdomains", [])
            ip_info = data.get("ip_info", {})

            sections += f"""
<div class="section">
    <div class="section-header"><h2>🕵️ OSINT Intelligence</h2></div>
    <div class="section-body">
        <div style="display:grid; grid-template-columns:1fr 1fr; gap:20px;">
            <div>
                <h3 style="color:#888; margin-bottom:10px;">IP Information</h3>
                <table>
                    {''.join([f"<tr><td>{k.title()}</td><td>{v}</td></tr>" for k, v in ip_info.items() if k != 'ip'])}
                </table>
            </div>
            <div>
                <h3 style="color:#888; margin-bottom:10px;">DNS Records</h3>
                <table>
                    {''.join([f"<tr><td>{k}</td><td>{'<br>'.join(v) if isinstance(v, list) else v}</td></tr>" for k, v in dns.items() if v])}
                </table>
            </div>
        </div>
        <br>
        <h3 style="color:#888; margin-bottom:10px;">Subdomains Found ({len(subdomains)})</h3>
        <div>{''.join([f'<span class="tag">{s}</span>' for s in subdomains[:30]])}</div>
    </div>
</div>"""

        return sections if sections else "<p style='text-align:center; padding:40px; color:#444;'>No scan data available</p>"

    def generate_json_report(self, scan_data: dict, report_type: str = "general") -> str:
        """Save raw scan data as JSON"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"{self.output_dir}/cyberguard_{report_type}_{timestamp}.json"
        with open(filename, "w") as f:
            json.dump(scan_data, f, indent=2, default=str)
        return filename

    def generate_text_report(self, scan_data: dict) -> str:
        """Generate a simple text report"""
        lines = [
            "=" * 60,
            "         CYBERGUARD PRO - SECURITY REPORT",
            "=" * 60,
            f"Target  : {scan_data.get('target', 'N/A')}",
            f"Time    : {scan_data.get('timestamp', 'N/A')}",
            "=" * 60
        ]
        if "open_ports" in scan_data:
            lines.append(f"\n[NETWORK] Open Ports: {len(scan_data['open_ports'])}")
            for p in scan_data["open_ports"]:
                lines.append(f"  - Port {p['port']}/{p['service']} [{p['state']}]")

        if "vulnerabilities" in scan_data:
            lines.append(f"\n[WEB] Vulnerabilities: {len(scan_data['vulnerabilities'])}")
            for v in scan_data["vulnerabilities"]:
                lines.append(f"  - [{v['severity']}] {v['type']} in param '{v.get('parameter', 'N/A')}'")

        lines.append("\n" + "=" * 60)
        lines.append("Generated by CyberGuard Pro v1.0.0")
        return "\n".join(lines)
